namespace JobApplicationSpam
module Deutsch =
    open Types
    [<WebSharper.JavaScript>]
    let dict =
        [ AddEmployerAndApply, "Bewerben"
          EditYourValues, "Deine Daten"
          EditEmail, "Email"
          EditAttachments, "Anhänge"
          YourApplicationDocuments, "Deine Bewerbungsunterlagen"
          LoadFromWebsite, "Von Website lesen"
          ApplyNow, "Jetzt bewerben"
          CompanyName, "Firmenname"
          Street, "Straße"
          Postcode, "Postleitzahl"
          City, "Stadt"
          Gender, "Geschlecht"
          Degree, "Titel"
          FirstName, "Vorname"
          LastName, "Nachname"
          Email, "Email"
          Phone, "Telefonnummer"
          MobilePhone, "Mobilnummer"
          YourValues, "Deine Daten"
          EmailSubject, "Betreff"
          EmailBody, "Text"
          YourAttachments, "Deine Anhänge"
          CreateOnline, "Online erstellen"
          UploadFile, "Datei hochladen"
          PleaseChooseAFile, "Bitte eine Datei aussuchen"
          AddAttachment, "Anhang hinzufügen"
          YouMightWantToReplaceSomeWordsInYourFileWithVariables, "Vielleicht möchtest du einige Worte in deiner Datei durch Variablen ersetzen."
          VariablesWillBeReplacedWithTheRightValuesEveryTimeYouSendYourApplication, "Jedesmal, wenn du eine Bewerbung versendest, werden die Variablen automatisch durch die richtigen Werte ersetzt."
          Male, "männlich"
          Female, "weiblich"
          UnknownGender, "unbekannt"
          AddDocument, "Dokument hinzufügen"
          DocumentName, "Name des Dokuments"
          AddHtmlAttachment, "Html Anhang hinzufügen"
          Employer, "Arbeitgeber"
          JustDownload, "Nur downloaden"
          DownloadWithReplacedVariables, "Variablen ersetzen und downloaden"
          ReallyDeleteDocument, """Document "{0}" wirklich löschen?"""
          ReallyDeletePage, """Seite "{0}" wirklich löschen?"""
          PleaseConfirmYourEmailAddressEmailSubject, "Bitte bestätige deine Email-Adresse"
          PleaseConfirmYourEmailAddressEmailBody, "Hallo!\n\nBitte besuche den folgenden Link, um deine Email-Adresse zu bestätigen.\nhttp://bewerbungsspam.de/confirmemail?email={0}&guid={1}\n\nDein Team von www.bewerbungsspam.de"
          Login, "Einloggen"
          Register, "Registrieren"
          SentApplications, "Versandte Bewerbungen"
          JobName, "Bewerben als"
          AppliedAs, "Beworben als"
          AppliedOnDate, "Beworben am"
          TheEmailOfYourEmployerDoesNotLookValid, "Die Email-Adresse des Arbeitgeber scheint fehlerhaft zu sein."
          FieldIsRequired, """Feld "{0}" darf nicht leer sein."""
          SorryAnErrorOccurred, "Entschuldigung, es ist ein Fehler aufgetreten."
          YourApplicationHasNotBeenSent, "Deine Bewerbung konnte nicht versendet werden :-("
        ]



