namespace JobApplicationSpam
module Deutsch =
    open Types
    [<WebSharper.JavaScript>]
    let dict =
        [ AddEmployerAndApply, "Bewerben"
          EditYourValues, "Deine Daten"
          EditEmail, "Email"
          EditAttachments, "Anhänge"
          YourApplicationDocuments, "Deine Bewerbungsunterlagen"
          LoadFromWebsite, "Von Website lesen"
          ApplyNow, "Jetzt bewerben"
          CompanyName, "Firmenname"
          Street, "Straße"
          Postcode, "Postleitzahl"
          City, "Stadt"
          Gender, "Geschlecht"
          Degree, "Titel"
          FirstName, "Vorname"
          LastName, "Nachname"
          Email, "Email"
          Phone, "Telefonnummer"
          MobilePhone, "Mobilnummer"
          YourValues, "Deine Daten"
          EmailSubject, "Betreff"
          EmailBody, "Text"
          YourAttachments, "Deine Anhänge"
          CreateOnline, "Online erstellen"
          UploadFile, "Datei hochladen"
          PleaseChooseAFile, "Bitte eine Datei aussuchen"
          AddAttachment, "Anhang hinzufügen"
          YouMightWantToReplaceSomeWordsInYourFileWithVariables, "Vielleicht möchtest du einige Wörter in deiner Datei durch Variablen ersetzen."
          VariablesWillBeReplacedWithTheRightValuesEveryTimeYouSendYourApplication, "Variablen werden bei jedem Versenden einer Bewerbung durch die richtigen Werte ersetzt."
          Male, "männlich"
          Female, "weiblich"
          UnknownGender, "unbekannt"
          AddDocument, "Dokument hinzufügen"
          DocumentName, "Name des Dokuments"
          AddHtmlAttachment, "Html Anhang hinzufügen"
          Employer, "Arbeitgeber"
          JustDownload, "Nur downloaden"
          DownloadWithReplacedVariables, "Variablen ersetzen und downloaden"
          ReallyDeleteDocument, "Document {0} wirklich löschen?" 
          ReallyDeletePage, "Seite {0} wirklich löschen?"
        ]
