namespace JobApplicationSpam
module English =
    open Types

    let dict =
        [ AddEmployerAndApply, "Add employer and apply"
          EditYourValues, "Edit your values"
          EditEmail, "Edit email"
          EditAttachments, "Edit attachments"
          YourApplicationDocuments, "Your applicationDocuments"
          LoadFromWebsite, "LoadFromWebsite"
          ApplyNow, "Apply now"
          CompanyName, "Company name"
          Street, "Street"
          Postcode, "Postcode"
          City, "City"
          Gender, "Gender"
          Degree, "Degree"
          FirstName, "First name"
          LastName, "Last name"
          Email, "Email"
          Phone, "Phone"
          MobilePhone, "Mobile phone"
          YourValues, "Your values"
          EmailSubject, "Subject"
          EmailBody, "Body"
          YourAttachments, "Your attachments"
          CreateOnline, "Create online"
          UploadFile, "Upload a file"
          PleaseChooseAFile, "Please choose a file"
          AddAttachment, "Add attachment"
          YouMightWantToReplaceSomeWordsInYourFileWithVariables, "You might want to replace some words in your file with variables"
          VariablesWillBeReplacedWithTheRightValuesEveryTimeYouSendYourApplication, "Variables will be replaced with the right values every time you send your application."
          ReallyDeleteDocument, "Really delete document {0}?" 
          Male, "male"
          Female, "female"
          AddDocument, "Add document"
          DocumentName, "Document name: "
          AddHtmlAttachment, "Add Html attachment"
          Employer, "Employer"
        ]