namespace JobApplicationSpam
module German =
    open Phrases

    [<WebSharper.JavaScript>]
    let t x =
        match x with
        | AddEmployerAndApply -> "Bewerben"
        | EditYourValues -> "Deine Daten"
        | EditEmail -> "Email"
        | EditAttachments -> "Anhänge"
        | YourApplicationDocuments -> "Deine Bewerbungsmappen"
        | LoadFromWebsite -> "Werte holen"
        | ApplyNow -> "Jetzt bewerben"
        | CompanyName -> "Firmenname"
        | Street -> "Straße"
        | Postcode -> "Postleitzahl"
        | City -> "Stadt"
        | Gender -> "Geschlecht"
        | Degree -> "Titel"
        | FirstName -> "Vorname"
        | LastName -> "Nachname"
        | Email -> "Email"
        | Phone -> "Telefonnummer"
        | MobilePhone -> "Mobilnummer"
        | YourValues -> "Deine Daten"
        | EmailSubject -> "Betreff"
        | EmailBody -> "Text"
        | YourAttachments -> "Anhänge"
        | CreateOnline -> "Online erstellen"
        | UploadFile -> "Datei hochladen"
        | PleaseChooseAFile -> "Bitte eine Datei aussuchen"
        | AddAttachment -> "Anhang hinzufügen"
        | YouMightWantToReplaceSomeWordsInYourFileWithVariables -> "Du kannst Worte oder Phrasen in deiner Datei durch Variablen ersetzen."
        | VariablesWillBeReplacedWithTheRightValuesEveryTimeYouSendYourApplication -> "Jedesmal, wenn du eine Bewerbung versendest, werden die Variablen automatisch durch die richtigen Werte ersetzt."
        | Male -> "männlich"
        | Female -> "weiblich"
        | UnknownGender -> "unbekannt"
        | AddDocument -> "Bewerbungsmappe hinzufügen"
        | DocumentName -> "Name der Bewerbungsmappe"
        | AddHtmlAttachment -> "Html Anhang hinzufügen"
        | Employer -> "Arbeitgeber"
        | Download -> "downloaden"
        | ReallyDeleteDocument -> """Document "{0}" wirklich löschen?"""
        | ReallyDeletePage -> """Seite "{0}" wirklich löschen?"""
        | WeHaveSentYouAnEmail -> "Wir haben dir eine Email geschickt."
        | PleaseConfirmYourEmailAddressEmailSubject -> "Bitte bestätige deine Email-Adresse"
        | PleaseConfirmYourEmailAddressEmailBody -> "Lieber Benutzer,\n\ndu hast zur Zeit nur einen einwöchigen Gast-Zugang. Bitte besuche den folgenden Link, um dauerhaft gratis Vollzugang zu erhalten.\nhttps://bewerbungsspam.de/confirmemail?email={0}&guid={1}\n\nDein Team von www.bewerbungsspam.de"
        | Login -> "Einloggen"
        | Register -> "Registrieren"
        | SentApplications -> "Versandte Bewerbungen"
        | JobName -> "Bewerben als"
        | AppliedAs -> "Beworben als"
        | AppliedOnDate -> "Beworben am"
        | TheEmailOfYourEmployerDoesNotLookValid -> "Die Email-Adresse des Arbeitgeber scheint fehlerhaft zu sein."
        | FieldIsRequired -> """Feld "{0}" darf nicht leer sein."""
        | SorryAnErrorOccurred -> "Entschuldigung, es ist ein Fehler aufgetreten."
        | YourApplicationHasNotBeenSent -> "Deine Bewerbung konnte nicht versendet werden :-("
        | FileIsTooBig -> "Die ausgewählte Datei ist zu groß."
        | UploadLimit -> "Die maximale Dateigröße beträgt {0} MB."
        | ReplaceVariables -> "Variablen ersetzen"
        | ChangePassword -> "Passwort ändern"
        | NewPassword -> "Neues Passwort"
